### ISSUE TITLE
this workflow doesn't work completely

### ISSUE THREAD

**Issue by quanxin** [burdo3417/GPTChat-workflow#1]
Hi，thank you for providing this convenient workflow .
i am using this workflow on my mac recently, the "ask" command works, after i input some words after the command, it can launch the ChatGPT app installed on my mac, however, the workflow didn't copy my inputs to the app.
any suggestion will be grateful, thanks

**Comment by burdo3417** [comment]
try opening the app and leaving the blinking cursor on the text field where you type on.

Press ESC to minimize the app and try again using alfred

**Comment by quanxin** [comment]
> try opening the app and leaving the blinking cursor on the text field where you type on.
> 
> Press ESC to minimize the app and try again using alfred

thank you so much, it works.

**Comment by Ayoubaby** [comment]
Hey, currently having the same issue but the solution above didn't work for me. Pressing esc doesn't minimize the app on the menu bar. Any fix to this ?
